version: '3'

services:
  mysql:
    hostname: sql_http_mysql
    image: mysql:5.7
    ports:
      - '3308:3306'
    environment:
        MYSQL_ROOT_PASSWORD: test_password_root
        MYSQL_DATABASE: test_db
        MYSQL_USER: test_user
        MYSQL_PASSWORD: test_password
  sql_http:
    hostname: sql_http_api
    ports:
      - '8081:8081'
    environment:
      PORT: '8081'
    build:
      context: ./server
      dockerfile: Dockerfile