package kperson.sqlh.common

import ExecuteWrite._
import ExecuteQuery._
import kperson.sqlh.common.ExecuteBatchWrite.BatchWriteExecuteExtension

class CommandRunner(resolvers: List[DataSourceReferenceResolver] = List()) {

  def run(command: SQLCommand): CommandResponse = {
    command match {
      case q: Query => QueryResponse(q.run(resolvers))
      case w: Write => w.run(resolvers)
      case w: BatchWrite => w.run(resolvers)

    }
  }

}


sealed trait CommandResponse
case class WriteResponse(numberOfAffectedRows: Int, autoGeneratedKeys: List[String]) extends CommandResponse
case class BatchWriteResponse(numberOfAffectedRows: List[Int]) extends CommandResponse
case class QueryResponse(rows: List[Row]) extends CommandResponse